-- Curated question bank (generated by scripts/build-question-migration.mjs from data/question-bank.json).
-- Replaces the trivial starter_seed bank: real tiered trivia, 5 questions per state.
-- Also: when a player has seen every question for a state, recycle the least
-- recently served one instead of failing the action.

update public.questions set active = false where validation_status = 'starter_seed';

insert into public.questions(territory_id, sport, link_type, tier, format, question_text, options, correct_answer, aliases, validation_status)
select v.territory_id, v.sport, v.link_type, v.tier, v.format, v.question_text, v.options, v.correct_answer, v.aliases, 'curated_v1'
from (values
('AL', 'CFB', 'curated', 1, 'multiple_choice', 'The Alabama Crimson Tide compete in which conference?', '["SEC","Big Ten","ACC","Big 12"]'::jsonb, 'SEC', array[]::text[]),
('AL', 'CFB', 'curated', 2, 'multiple_choice', 'Which coach won six national championships at Alabama between 2009 and 2020?', '["Nick Saban","Gene Stallings","Urban Meyer","Dabo Swinney"]'::jsonb, 'Nick Saban', array[]::text[]),
('AL', 'CFB', 'curated', 2, 'multiple_choice', 'Which quarterback led Auburn to the 2010 BCS national championship?', '["Cam Newton","Jason Campbell","Bo Nix","Nick Marshall"]'::jsonb, 'Cam Newton', array[]::text[]),
('AL', 'CFB', 'curated', 3, 'free_fill', 'Name the legendary Alabama coach known for his houndstooth hat and 323 career wins.', '[]'::jsonb, 'Paul Bear Bryant', array['Bear Bryant','Bryant','Paul Bryant']::text[]),
('AL', 'CFB', 'curated', 3, 'free_fill', 'Which Alabama receiver won the 2020 Heisman Trophy?', '[]'::jsonb, 'DeVonta Smith', array['Smith','Devonta Smith']::text[]),
('AK', 'OTH', 'curated', 1, 'multiple_choice', 'The Alaska Nanooks are best known for competing in which NCAA sport?', '["Ice hockey","Football","Baseball","Lacrosse"]'::jsonb, 'Ice hockey', array[]::text[]),
('AK', 'MLB', 'curated', 2, 'multiple_choice', 'Which three-time World Series champion pitcher was born in Anchorage?', '["Curt Schilling","Randy Johnson","Jon Lester","Tom Glavine"]'::jsonb, 'Curt Schilling', array[]::text[]),
('AK', 'NBA', 'curated', 2, 'multiple_choice', 'Which NBA champion forward grew up in Juneau, Alaska?', '["Carlos Boozer","Paul Millsap","Al Horford","David West"]'::jsonb, 'Carlos Boozer', array[]::text[]),
('AK', 'NFL', 'curated', 3, 'free_fill', 'Name the Anchorage-raised NFL guard who won three Super Bowls with Washington and Denver.', '[]'::jsonb, 'Mark Schlereth', array['Schlereth']::text[]),
('AK', 'OTH', 'curated', 3, 'free_fill', 'What famous long-distance sled dog race runs from Anchorage to Nome?', '[]'::jsonb, 'Iditarod', array['The Iditarod','Iditarod Trail Sled Dog Race']::text[]),
('AZ', 'MLB', 'curated', 1, 'multiple_choice', 'Which Arizona team won the 2001 World Series?', '["Arizona Diamondbacks","Arizona Cardinals","Phoenix Suns","Arizona Coyotes"]'::jsonb, 'Arizona Diamondbacks', array[]::text[]),
('AZ', 'MLB', 'curated', 2, 'multiple_choice', 'Whose walk-off hit off Mariano Rivera won Game 7 of the 2001 World Series?', '["Luis Gonzalez","Craig Counsell","Mark Grace","Matt Williams"]'::jsonb, 'Luis Gonzalez', array[]::text[]),
('AZ', 'NBA', 'curated', 2, 'multiple_choice', 'Which Suns forward won the 1993 NBA MVP award?', '["Charles Barkley","Kevin Johnson","Dan Majerle","Steve Nash"]'::jsonb, 'Charles Barkley', array[]::text[]),
('AZ', 'NFL', 'curated', 3, 'free_fill', 'Name the Cardinals safety who left the NFL in 2002 to enlist in the U.S. Army.', '[]'::jsonb, 'Pat Tillman', array['Tillman']::text[]),
('AZ', 'NFL', 'curated', 3, 'free_fill', 'Which quarterback led the Cardinals to Super Bowl XLIII?', '[]'::jsonb, 'Kurt Warner', array['Warner']::text[]),
('AR', 'CFB', 'curated', 1, 'multiple_choice', 'What chant do Arkansas Razorbacks fans use to call the Hogs?', '["Woo Pig Sooie","Roll Tide","War Eagle","Boomer Sooner"]'::jsonb, 'Woo Pig Sooie', array[]::text[]),
('AR', 'NFL', 'curated', 2, 'multiple_choice', 'Which NFL owner played on Arkansas''s 1964 national championship team?', '["Jerry Jones","Robert Kraft","Stan Kroenke","Arthur Blank"]'::jsonb, 'Jerry Jones', array[]::text[]),
('AR', 'NBA', 'curated', 2, 'multiple_choice', 'Which six-time NBA champion from Hamburg, Arkansas played at Central Arkansas?', '["Scottie Pippen","Horace Grant","Dennis Rodman","Ron Harper"]'::jsonb, 'Scottie Pippen', array[]::text[]),
('AR', 'OTH', 'curated', 3, 'free_fill', 'Name the Arkansas golfer who won the 1991 PGA Championship as the ninth alternate.', '[]'::jsonb, 'John Daly', array['Daly']::text[]),
('AR', 'CFB', 'curated', 3, 'free_fill', 'Which Razorbacks running back won the Doak Walker Award twice and was the 2008 NFL draft''s fourth pick?', '[]'::jsonb, 'Darren McFadden', array['McFadden']::text[]),
('CA', 'NBA', 'curated', 1, 'multiple_choice', 'Which NBA team set the regular-season wins record at 73-9 in 2015-16?', '["Golden State Warriors","Los Angeles Lakers","Sacramento Kings","LA Clippers"]'::jsonb, 'Golden State Warriors', array[]::text[]),
('CA', 'MLB', 'curated', 2, 'multiple_choice', 'Who hit the injured-leg, walk-off homer for the Dodgers in Game 1 of the 1988 World Series?', '["Kirk Gibson","Steve Sax","Mike Scioscia","Orel Hershiser"]'::jsonb, 'Kirk Gibson', array[]::text[]),
('CA', 'MLB', 'curated', 2, 'multiple_choice', 'Which Padres legend won eight National League batting titles?', '["Tony Gwynn","Dave Winfield","Steve Garvey","Trevor Hoffman"]'::jsonb, 'Tony Gwynn', array[]::text[]),
('CA', 'NFL', 'curated', 3, 'free_fill', 'Name the 49ers quarterback who went 4-0 in Super Bowls.', '[]'::jsonb, 'Joe Montana', array['Montana']::text[]),
('CA', 'NBA', 'curated', 3, 'free_fill', 'Which Lakers center scored 38,387 career points, the record Kareem held until 2023 — full name, please.', '[]'::jsonb, 'Kareem Abdul-Jabbar', array['Kareem','Abdul-Jabbar','Abdul Jabbar']::text[]),
('CO', 'NFL', 'curated', 1, 'multiple_choice', 'What is the nickname of Denver''s NFL stadium''s famous altitude advantage?', '["Mile High","Sky High","Rocky Top","Thin Air"]'::jsonb, 'Mile High', array[]::text[]),
('CO', 'NFL', 'curated', 2, 'multiple_choice', 'Which quarterback won back-to-back Super Bowls with the Broncos in the late 1990s?', '["John Elway","Peyton Manning","Jake Plummer","Brian Griese"]'::jsonb, 'John Elway', array[]::text[]),
('CO', 'NHL', 'curated', 2, 'multiple_choice', 'The Colorado Avalanche won the Stanley Cup in their first Denver season. What year?', '["1996","1994","1999","2001"]'::jsonb, '1996', array[]::text[]),
('CO', 'MLB', 'curated', 3, 'free_fill', 'Name the Rockies first baseman whose No. 17 was the first number the franchise retired.', '[]'::jsonb, 'Todd Helton', array['Helton']::text[]),
('CO', 'NHL', 'curated', 3, 'free_fill', 'Which Avalanche captain lifted both the 1996 and 2001 Stanley Cups?', '[]'::jsonb, 'Joe Sakic', array['Sakic']::text[]),
('CT', 'CBB', 'curated', 1, 'multiple_choice', 'UConn''s men won back-to-back national titles in 2023 and 2024 under which coach?', '["Dan Hurley","Jim Calhoun","Kevin Ollie","Bobby Hurley"]'::jsonb, 'Dan Hurley', array[]::text[]),
('CT', 'CBB', 'curated', 2, 'multiple_choice', 'Who has coached the UConn women''s program since 1985?', '["Geno Auriemma","Pat Summitt","Muffet McGraw","Tara VanDerveer"]'::jsonb, 'Geno Auriemma', array[]::text[]),
('CT', 'NHL', 'curated', 2, 'multiple_choice', 'Hartford''s NHL team left Connecticut in 1997. What were they called?', '["Whalers","Nordiques","Americans","Mariners"]'::jsonb, 'Whalers', array[]::text[]),
('CT', 'CBB', 'curated', 3, 'free_fill', 'Name the guard who carried UConn on an 11-game postseason run to the 2011 title.', '[]'::jsonb, 'Kemba Walker', array['Kemba','Walker']::text[]),
('CT', 'CBB', 'curated', 3, 'free_fill', 'Which UConn star was the top pick of the 2025 WNBA draft?', '[]'::jsonb, 'Paige Bueckers', array['Bueckers']::text[]),
('DE', 'CFB', 'curated', 1, 'multiple_choice', 'What is the University of Delaware''s football nickname?', '["Fightin'' Blue Hens","Terrapins","Owls","Tigers"]'::jsonb, 'Fightin'' Blue Hens', array[]::text[]),
('DE', 'NFL', 'curated', 2, 'multiple_choice', 'Which Super Bowl XLVII MVP quarterback played college ball at Delaware?', '["Joe Flacco","Nick Foles","Carson Wentz","Eli Manning"]'::jsonb, 'Joe Flacco', array[]::text[]),
('DE', 'NFL', 'curated', 2, 'multiple_choice', 'Which Delaware alum won the 2002 NFL MVP with the Raiders?', '["Rich Gannon","Jeff Hostetler","Daryle Lamonica","Ken Stabler"]'::jsonb, 'Rich Gannon', array[]::text[]),
('DE', 'OTH', 'curated', 3, 'free_fill', 'Name the Delaware native and Blue Hens star who became a WNBA MVP with Chicago and Washington.', '[]'::jsonb, 'Elena Delle Donne', array['Delle Donne']::text[]),
('DE', 'NFL', 'curated', 3, 'free_fill', 'Joe Flacco''s Super Bowl MVP came in which Super Bowl (number or team beaten)?', '[]'::jsonb, 'XLVII', array['47','Super Bowl XLVII','49ers','San Francisco']::text[]),
('FL', 'NFL', 'curated', 1, 'multiple_choice', 'Which Florida team completed the NFL''s only perfect season in 1972?', '["Miami Dolphins","Tampa Bay Buccaneers","Jacksonville Jaguars","Orlando Renegades"]'::jsonb, 'Miami Dolphins', array[]::text[]),
('FL', 'CFB', 'curated', 2, 'multiple_choice', 'Who became the first sophomore to win the Heisman Trophy, at Florida in 2007?', '["Tim Tebow","Danny Wuerffel","Steve Spurrier","Percy Harvin"]'::jsonb, 'Tim Tebow', array[]::text[]),
('FL', 'MLB', 'curated', 2, 'multiple_choice', 'The Marlins won the World Series in 2003 and which other year?', '["1997","1993","2000","2008"]'::jsonb, '1997', array[]::text[]),
('FL', 'NFL', 'curated', 3, 'free_fill', 'Name the Dolphins quarterback who retired holding nearly every passing record but never won a Super Bowl.', '[]'::jsonb, 'Dan Marino', array['Marino']::text[]),
('FL', 'CFB', 'curated', 3, 'free_fill', 'Which Florida State quarterback won the 1993 Heisman and then played point guard for the Knicks?', '[]'::jsonb, 'Charlie Ward', array['Ward']::text[]),
('GA', 'MLB', 'curated', 1, 'multiple_choice', 'Hank Aaron hit his record-breaking 715th home run in 1974 playing for which team?', '["Atlanta Braves","Milwaukee Brewers","New York Mets","Cincinnati Reds"]'::jsonb, 'Atlanta Braves', array[]::text[]),
('GA', 'CFB', 'curated', 2, 'multiple_choice', 'Georgia won back-to-back national titles in the 2021 and 2022 seasons under which coach?', '["Kirby Smart","Mark Richt","Vince Dooley","Jim Donnan"]'::jsonb, 'Kirby Smart', array[]::text[]),
('GA', 'CFB', 'curated', 2, 'multiple_choice', 'Which Georgia running back won the 1982 Heisman Trophy?', '["Herschel Walker","Garrison Hearst","Todd Gurley","Nick Chubb"]'::jsonb, 'Herschel Walker', array[]::text[]),
('GA', 'NFL', 'curated', 3, 'free_fill', 'What infamous lead did the Falcons hold in Super Bowl LI before losing in overtime?', '[]'::jsonb, '28-3', array['28 3','28 to 3','twenty eight to three']::text[]),
('GA', 'MLB', 'curated', 3, 'free_fill', 'Name the Braves pitcher who won the 1995 World Series MVP with a one-hit Game 6.', '[]'::jsonb, 'Tom Glavine', array['Glavine']::text[]),
('HI', 'CFB', 'curated', 1, 'multiple_choice', 'What is the University of Hawaii''s football nickname?', '["Rainbow Warriors","Islanders","Volcanoes","Wavecrashers"]'::jsonb, 'Rainbow Warriors', array[]::text[]),
('HI', 'CFB', 'curated', 2, 'multiple_choice', 'Which record-setting quarterback led Hawaii to the 2008 Sugar Bowl?', '["Colt Brennan","Marcus Mariota","Timmy Chang","Tua Tagovailoa"]'::jsonb, 'Colt Brennan', array[]::text[]),
('HI', 'OTH', 'curated', 2, 'multiple_choice', 'Which Honolulu-born golfer won the 2014 U.S. Women''s Open?', '["Michelle Wie","Lydia Ko","Paula Creamer","Inbee Park"]'::jsonb, 'Michelle Wie', array[]::text[]),
('HI', 'OTH', 'curated', 3, 'free_fill', 'Name the Hawaiian Olympic swimming champion credited with popularizing modern surfing.', '[]'::jsonb, 'Duke Kahanamoku', array['Duke','Kahanamoku']::text[]),
('HI', 'NFL', 'curated', 3, 'free_fill', 'Which Honolulu-born quarterback won the 2014 Heisman Trophy?', '[]'::jsonb, 'Marcus Mariota', array['Mariota']::text[]),
('ID', 'CFB', 'curated', 1, 'multiple_choice', 'Boise State''s home field is famous for what?', '["Blue turf","Retractable roof","Grass painted gold","Playing on dirt"]'::jsonb, 'Blue turf', array[]::text[]),
('ID', 'CFB', 'curated', 2, 'multiple_choice', 'Boise State beat Oklahoma in the 2007 Fiesta Bowl on which trick play two-point conversion?', '["Statue of Liberty","Flea flicker","Fumblerooski","Hook and ladder"]'::jsonb, 'Statue of Liberty', array[]::text[]),
('ID', 'MLB', 'curated', 2, 'multiple_choice', 'Which 573-homer Hall of Famer from Payette, Idaho starred for the Twins?', '["Harmon Killebrew","Rod Carew","Kirby Puckett","Tony Oliva"]'::jsonb, 'Harmon Killebrew', array[]::text[]),
('ID', 'OTH', 'curated', 3, 'free_fill', 'Name the Idaho-born skier who won Super-G gold at the 1998 Nagano Olympics.', '[]'::jsonb, 'Picabo Street', array['Picabo','Street']::text[]),
('ID', 'OTH', 'curated', 3, 'free_fill', 'Which Boise cyclist won three straight Olympic time-trial golds (2008-2016)?', '[]'::jsonb, 'Kristin Armstrong', array['Armstrong']::text[]),
('IL', 'NBA', 'curated', 1, 'multiple_choice', 'How many NBA championships did Michael Jordan win with the Bulls?', '["6","4","5","7"]'::jsonb, '6', array[]::text[]),
('IL', 'MLB', 'curated', 2, 'multiple_choice', 'The Cubs'' 2016 World Series win ended a drought of how many years?', '["108","86","95","100"]'::jsonb, '108', array[]::text[]),
('IL', 'MLB', 'curated', 2, 'multiple_choice', 'Which team did the White Sox sweep to win the 2005 World Series?', '["Houston Astros","St. Louis Cardinals","Boston Red Sox","Atlanta Braves"]'::jsonb, 'Houston Astros', array[]::text[]),
('IL', 'NFL', 'curated', 3, 'free_fill', 'Name the Bears running back nicknamed ''Sweetness.''', '[]'::jsonb, 'Walter Payton', array['Payton']::text[]),
('IL', 'NFL', 'curated', 3, 'free_fill', 'Which fearsome Bears linebacker has the NCAA''s top linebacker award named after him?', '[]'::jsonb, 'Dick Butkus', array['Butkus']::text[]),
('IN', 'OTH', 'curated', 1, 'multiple_choice', 'What famous race is run each May at Indianapolis Motor Speedway?', '["Indianapolis 500","Daytona 500","Brickyard 600","Hoosier Grand Prix"]'::jsonb, 'Indianapolis 500', array[]::text[]),
('IN', 'NBA', 'curated', 2, 'multiple_choice', 'Which Pacer scored 8 points in 9 seconds to stun the Knicks in the 1995 playoffs?', '["Reggie Miller","Rik Smits","Mark Jackson","Jalen Rose"]'::jsonb, 'Reggie Miller', array[]::text[]),
('IN', 'CBB', 'curated', 2, 'multiple_choice', 'The last undefeated men''s national champion was Indiana in which year?', '["1976","1981","1987","1972"]'::jsonb, '1976', array[]::text[]),
('IN', 'NBA', 'curated', 3, 'free_fill', 'Name the Hall of Famer from French Lick who led Indiana State to the 1979 title game.', '[]'::jsonb, 'Larry Bird', array['Bird']::text[]),
('IN', 'NFL', 'curated', 3, 'free_fill', 'Which Colts quarterback was MVP of rain-soaked Super Bowl XLI?', '[]'::jsonb, 'Peyton Manning', array['Peyton','Manning']::text[]),
('IA', 'CFB', 'curated', 1, 'multiple_choice', 'Iowa''s in-state football rivalry against Iowa State is called what?', '["Cy-Hawk","Corn Bowl","Hawkeye Classic","Prairie Showdown"]'::jsonb, 'Cy-Hawk', array[]::text[]),
('IA', 'CBB', 'curated', 2, 'multiple_choice', 'Which Iowa guard became NCAA Division I basketball''s all-time leading scorer in 2024?', '["Caitlin Clark","Megan Gustafson","Luka Garza","B.J. Armstrong"]'::jsonb, 'Caitlin Clark', array[]::text[]),
('IA', 'OTH', 'curated', 2, 'multiple_choice', 'Which wrestling legend won 1972 Olympic gold without surrendering a point, then coached Iowa to 15 team titles?', '["Dan Gable","Cael Sanderson","Tom Brands","John Smith"]'::jsonb, 'Dan Gable', array[]::text[]),
('IA', 'CFB', 'curated', 3, 'free_fill', 'Iowa''s stadium honors which 1939 Heisman winner who died in World War II?', '[]'::jsonb, 'Nile Kinnick', array['Kinnick']::text[]),
('IA', 'MLB', 'curated', 3, 'free_fill', 'In what Iowa town is the Field of Dreams ballfield?', '[]'::jsonb, 'Dyersville', array[]::text[]),
('KS', 'CBB', 'curated', 1, 'multiple_choice', 'Which Kansas school''s basketball program was first coached by the game''s inventor, James Naismith?', '["Kansas Jayhawks","Kansas State Wildcats","Wichita State Shockers","Washburn Ichabods"]'::jsonb, 'Kansas Jayhawks', array[]::text[]),
('KS', 'CBB', 'curated', 2, 'multiple_choice', 'Whose three-pointer forced overtime in Kansas''s 2008 title-game win over Memphis?', '["Mario Chalmers","Sherron Collins","Brandon Rush","Darrell Arthur"]'::jsonb, 'Mario Chalmers', array[]::text[]),
('KS', 'NFL', 'curated', 2, 'multiple_choice', 'Which Heisman-winning running back grew up in Wichita?', '["Barry Sanders","Marcus Allen","Billy Sims","Mike Rozier"]'::jsonb, 'Barry Sanders', array[]::text[]),
('KS', 'NFL', 'curated', 3, 'free_fill', 'Name the Bears Hall of Famer nicknamed the ''Kansas Comet.''', '[]'::jsonb, 'Gale Sayers', array['Sayers']::text[]),
('KS', 'CBB', 'curated', 3, 'free_fill', 'Kansas''s home arena is named for which long-time coach?', '[]'::jsonb, 'Phog Allen', array['Allen','Allen Fieldhouse','Forrest Allen']::text[]),
('KY', 'OTH', 'curated', 1, 'multiple_choice', 'The Kentucky Derby is run at which track?', '["Churchill Downs","Keeneland","Pimlico","Belmont Park"]'::jsonb, 'Churchill Downs', array[]::text[]),
('KY', 'OTH', 'curated', 2, 'multiple_choice', 'Which horse''s 1973 Derby record of 1:59 2/5 still stands?', '["Secretariat","Seattle Slew","Affirmed","Man o'' War"]'::jsonb, 'Secretariat', array[]::text[]),
('KY', 'CBB', 'curated', 2, 'multiple_choice', 'Kentucky''s Rupp Arena is named after which coach?', '["Adolph Rupp","Rick Pitino","Joe B. Hall","John Calipari"]'::jsonb, 'Adolph Rupp', array[]::text[]),
('KY', 'OTH', 'curated', 3, 'free_fill', 'Name the heavyweight champion from Louisville who won 1960 Olympic gold as Cassius Clay.', '[]'::jsonb, 'Muhammad Ali', array['Ali','Cassius Clay']::text[]),
('KY', 'CBB', 'curated', 3, 'free_fill', 'Which unibrowed freshman anchored Kentucky''s 2012 national championship team?', '[]'::jsonb, 'Anthony Davis', array['Davis','AD']::text[]),
('LA', 'NFL', 'curated', 1, 'multiple_choice', 'Which quarterback was MVP of the Saints'' Super Bowl XLIV win?', '["Drew Brees","Archie Manning","Jameis Winston","Aaron Brooks"]'::jsonb, 'Drew Brees', array[]::text[]),
('LA', 'CBB', 'curated', 2, 'multiple_choice', 'Which LSU guard averaged an NCAA-record 44.2 points per game?', '["Pete Maravich","Bob Pettit","Chris Jackson","Ben Simmons"]'::jsonb, 'Pete Maravich', array[]::text[]),
('LA', 'CFB', 'curated', 2, 'multiple_choice', 'Which quarterback won the 2019 Heisman and led 15-0 LSU to the title?', '["Joe Burrow","Jayden Daniels","Matt Mauck","JaMarcus Russell"]'::jsonb, 'Joe Burrow', array[]::text[]),
('LA', 'CBB', 'curated', 3, 'free_fill', 'What was Pete Maravich''s famous nickname?', '[]'::jsonb, 'Pistol Pete', array['Pistol','The Pistol']::text[]),
('LA', 'NBA', 'curated', 3, 'free_fill', 'Which dominant center won a national title culture at LSU before going first overall in the 1992 draft?', '[]'::jsonb, 'Shaquille O''Neal', array['Shaq','O''Neal','Shaquille Oneal']::text[]),
('ME', 'OTH', 'curated', 1, 'multiple_choice', 'The Maine Black Bears are a traditional power in which college sport?', '["Ice hockey","Football","Lacrosse","Soccer"]'::jsonb, 'Ice hockey', array[]::text[]),
('ME', 'OTH', 'curated', 2, 'multiple_choice', 'Which freshman won Maine''s first Hobey Baker Award during the 1993 title season?', '["Paul Kariya","Jimmy Howard","Scott Pellerin","Jack Capuano"]'::jsonb, 'Paul Kariya', array[]::text[]),
('ME', 'OTH', 'curated', 2, 'multiple_choice', 'Which Mainer won the first women''s Olympic marathon in 1984?', '["Joan Benoit","Mary Decker","Grete Waitz","Lynn Jennings"]'::jsonb, 'Joan Benoit', array[]::text[]),
('ME', 'OTH', 'curated', 3, 'free_fill', 'Maine won NCAA hockey titles in 1993 and which other year?', '[]'::jsonb, '1999', array[]::text[]),
('ME', 'MLB', 'curated', 3, 'free_fill', 'What Maine stadium-sharing summer league is famous for producing MLB stars using wooden bats? Hint: Cape ___.', '[]'::jsonb, 'Cape Cod League', array['Cape Cod','Cape Cod Baseball League']::text[]),
('MD', 'NFL', 'curated', 1, 'multiple_choice', 'The Baltimore Ravens take their name from a work by which writer?', '["Edgar Allan Poe","Mark Twain","H.L. Mencken","Frederick Douglass"]'::jsonb, 'Edgar Allan Poe', array[]::text[]),
('MD', 'MLB', 'curated', 2, 'multiple_choice', 'Cal Ripken Jr.''s consecutive-games streak ended at what number?', '["2,632","2,130","2,499","3,001"]'::jsonb, '2,632', array[]::text[]),
('MD', 'OTH', 'curated', 2, 'multiple_choice', 'Which Baltimore swimmer holds the record of 23 Olympic gold medals?', '["Michael Phelps","Mark Spitz","Ryan Lochte","Katie Ledecky"]'::jsonb, 'Michael Phelps', array[]::text[]),
('MD', 'NFL', 'curated', 3, 'free_fill', 'Name the linebacker who won MVP of Super Bowl XXXV for the Ravens.', '[]'::jsonb, 'Ray Lewis', array['Lewis']::text[]),
('MD', 'CBB', 'curated', 3, 'free_fill', 'Which Baltimore-raised guard led Maryland to its 2002 national championship?', '[]'::jsonb, 'Juan Dixon', array['Dixon']::text[]),
('MA', 'NBA', 'curated', 1, 'multiple_choice', 'Which franchise holds the most NBA championships?', '["Boston Celtics","Los Angeles Lakers","Chicago Bulls","Golden State Warriors"]'::jsonb, 'Boston Celtics', array[]::text[]),
('MA', 'MLB', 'curated', 2, 'multiple_choice', 'The 2004 Red Sox broke the Curse after coming back from what deficit against the Yankees?', '["Down 3-0","Down 3-1","Down 2-0","Down 3-2"]'::jsonb, 'Down 3-0', array[]::text[]),
('MA', 'NHL', 'curated', 2, 'multiple_choice', 'Which Bruin scored the flying Stanley Cup winner in 1970?', '["Bobby Orr","Phil Esposito","Ray Bourque","Cam Neely"]'::jsonb, 'Bobby Orr', array[]::text[]),
('MA', 'NBA', 'curated', 3, 'free_fill', 'Name the Celtics center who won 11 championships in 13 seasons.', '[]'::jsonb, 'Bill Russell', array['Russell']::text[]),
('MA', 'OTH', 'curated', 3, 'free_fill', 'The Boston Marathon is run on which Massachusetts holiday?', '[]'::jsonb, 'Patriots'' Day', array['Patriots Day','Patriot''s Day']::text[]),
('MI', 'CFB', 'curated', 1, 'multiple_choice', 'What is the nickname of Michigan Stadium, the largest in the country?', '["The Big House","The Horseshoe","Death Valley","The Swamp"]'::jsonb, 'The Big House', array[]::text[]),
('MI', 'NBA', 'curated', 2, 'multiple_choice', 'What was the nickname of the Pistons teams that won back-to-back titles in 1989 and 1990?', '["Bad Boys","Motor City Madmen","Goin'' to Work","Detroit Wall"]'::jsonb, 'Bad Boys', array[]::text[]),
('MI', 'CBB', 'curated', 2, 'multiple_choice', 'Michigan''s famed 1991 recruiting class of five freshman starters was known as what?', '["Fab Five","Fresh Five","Wolverine Wave","High Five"]'::jsonb, 'Fab Five', array[]::text[]),
('MI', 'NFL', 'curated', 3, 'free_fill', 'Which Lions running back walked away from the game in 1998, roughly 1,500 yards from the rushing record?', '[]'::jsonb, 'Barry Sanders', array['Sanders']::text[]),
('MI', 'NHL', 'curated', 3, 'free_fill', 'Name the Red Wings legend known as ''Mr. Hockey.''', '[]'::jsonb, 'Gordie Howe', array['Howe']::text[]),
('MN', 'NFL', 'curated', 1, 'multiple_choice', 'What was the nickname of the Vikings'' dominant 1970s defensive line?', '["Purple People Eaters","Steel Curtain","Doomsday Defense","Fearsome Foursome"]'::jsonb, 'Purple People Eaters', array[]::text[]),
('MN', 'MLB', 'curated', 2, 'multiple_choice', 'Whose Game 6 walk-off homer forced Game 7 of the 1991 World Series for the Twins?', '["Kirby Puckett","Kent Hrbek","Chili Davis","Dan Gladden"]'::jsonb, 'Kirby Puckett', array[]::text[]),
('MN', 'OTH', 'curated', 2, 'multiple_choice', 'Which St. Paul native coached the 1980 ''Miracle on Ice'' U.S. hockey team?', '["Herb Brooks","Lou Nanne","Bob Johnson","John Mariucci"]'::jsonb, 'Herb Brooks', array[]::text[]),
('MN', 'NBA', 'curated', 3, 'free_fill', 'Name the Timberwolves forward who won the 2004 NBA MVP.', '[]'::jsonb, 'Kevin Garnett', array['Garnett','KG']::text[]),
('MN', 'NFL', 'curated', 3, 'free_fill', 'Which Marshall, Minnesota-area franchise moment stings most: the Vikings have lost how many Super Bowls without a win?', '[]'::jsonb, '4', array['four']::text[]),
('MS', 'CFB', 'curated', 1, 'multiple_choice', 'What is Ole Miss''s famous cheer?', '["Hotty Toddy","War Eagle","Sic ''Em","Geaux Rebs"]'::jsonb, 'Hotty Toddy', array[]::text[]),
('MS', 'NFL', 'curated', 2, 'multiple_choice', 'Jerry Rice played his college football at which Mississippi school?', '["Mississippi Valley State","Ole Miss","Southern Miss","Jackson State"]'::jsonb, 'Mississippi Valley State', array[]::text[]),
('MS', 'NFL', 'curated', 2, 'multiple_choice', 'Which iron-man quarterback went from Southern Miss to a record 297 straight NFL starts?', '["Brett Favre","Steve McNair","Archie Manning","Ray Guy"]'::jsonb, 'Brett Favre', array[]::text[]),
('MS', 'NFL', 'curated', 3, 'free_fill', 'Walter Payton starred at which Mississippi HBCU?', '[]'::jsonb, 'Jackson State', array['Jackson State University']::text[]),
('MS', 'CFB', 'curated', 3, 'free_fill', 'Name the Ole Miss quarterback patriarch of football''s most famous QB family.', '[]'::jsonb, 'Archie Manning', array['Archie','Manning']::text[]),
('MO', 'NFL', 'curated', 1, 'multiple_choice', 'In which Missouri city do the Chiefs play?', '["Kansas City","St. Louis","Springfield","Columbia"]'::jsonb, 'Kansas City', array[]::text[]),
('MO', 'MLB', 'curated', 2, 'multiple_choice', 'The Royals won the 2015 World Series over which team?', '["New York Mets","San Francisco Giants","Philadelphia Phillies","Los Angeles Dodgers"]'::jsonb, 'New York Mets', array[]::text[]),
('MO', 'MLB', 'curated', 2, 'multiple_choice', 'Which National League franchise has the most World Series titles, with 11?', '["St. Louis Cardinals","Los Angeles Dodgers","San Francisco Giants","Atlanta Braves"]'::jsonb, 'St. Louis Cardinals', array[]::text[]),
('MO', 'MLB', 'curated', 3, 'free_fill', 'Name the Cardinals great known as ''Stan the Man.''', '[]'::jsonb, 'Stan Musial', array['Musial']::text[]),
('MO', 'NFL', 'curated', 3, 'free_fill', 'Patrick Mahomes won his first Super Bowl against which team?', '[]'::jsonb, 'San Francisco 49ers', array['49ers','Niners','San Francisco']::text[]),
('MT', 'CFB', 'curated', 1, 'multiple_choice', 'Montana vs. Montana State is known as what?', '["Brawl of the Wild","Big Sky Bowl","Treasure Trophy","Grizzly-Cat Classic"]'::jsonb, 'Brawl of the Wild', array[]::text[]),
('MT', 'MLB', 'curated', 2, 'multiple_choice', 'Which Orioles pitcher from Billings hit a grand slam in the 1970 World Series?', '["Dave McNally","Jim Palmer","Mike Cuellar","Pat Dobson"]'::jsonb, 'Dave McNally', array[]::text[]),
('MT', 'NBA', 'curated', 2, 'multiple_choice', 'Which 11-time champion NBA coach was born in Deer Lodge, Montana?', '["Phil Jackson","Pat Riley","Gregg Popovich","Red Auerbach"]'::jsonb, 'Phil Jackson', array[]::text[]),
('MT', 'NFL', 'curated', 3, 'free_fill', 'Name the Great Falls quarterback taken No. 2 overall in 1998, one pick after Peyton Manning.', '[]'::jsonb, 'Ryan Leaf', array['Leaf']::text[]),
('MT', 'OTH', 'curated', 3, 'free_fill', 'Which Butte, Montana daredevil famously jumped the Caesars Palace fountain on a motorcycle?', '[]'::jsonb, 'Evel Knievel', array['Knievel']::text[]),
('NE', 'CFB', 'curated', 1, 'multiple_choice', 'Nebraska''s Memorial Stadium has sold out every home game since what decade?', '["1960s","1980s","1990s","2000s"]'::jsonb, '1960s', array[]::text[]),
('NE', 'CFB', 'curated', 2, 'multiple_choice', 'Which coach led Nebraska to back-to-back national titles in 1994 and 1995?', '["Tom Osborne","Bob Devaney","Frank Solich","Bill Callahan"]'::jsonb, 'Tom Osborne', array[]::text[]),
('NE', 'MLB', 'curated', 2, 'multiple_choice', 'Which Omaha-born Cardinals ace posted a 1.12 ERA in 1968?', '["Bob Gibson","Curt Flood","Steve Carlton","Lou Brock"]'::jsonb, 'Bob Gibson', array[]::text[]),
('NE', 'CFB', 'curated', 3, 'free_fill', 'Name the Nebraska ''Johnny the Jet'' who won the 1972 Heisman.', '[]'::jsonb, 'Johnny Rodgers', array['Rodgers']::text[]),
('NE', 'OTH', 'curated', 3, 'free_fill', 'The College World Series has been played in which Nebraska city since 1950?', '[]'::jsonb, 'Omaha', array[]::text[]),
('NV', 'NFL', 'curated', 1, 'multiple_choice', 'Which NFL team relocated to Las Vegas in 2020?', '["Raiders","Chargers","Rams","Cardinals"]'::jsonb, 'Raiders', array[]::text[]),
('NV', 'CBB', 'curated', 2, 'multiple_choice', 'UNLV''s Runnin'' Rebels crushed Duke 103-73 in the title game in which year?', '["1990","1987","1993","1984"]'::jsonb, '1990', array[]::text[]),
('NV', 'NHL', 'curated', 2, 'multiple_choice', 'The Vegas Golden Knights won their first Stanley Cup in which year?', '["2023","2018","2021","2024"]'::jsonb, '2023', array[]::text[]),
('NV', 'OTH', 'curated', 3, 'free_fill', 'Name the Las Vegas tennis legend who completed a career Golden Slam.', '[]'::jsonb, 'Andre Agassi', array['Agassi']::text[]),
('NV', 'NHL', 'curated', 3, 'free_fill', 'In their inaugural 2017-18 season, the Golden Knights lost the Cup Final to which team?', '[]'::jsonb, 'Washington Capitals', array['Capitals','Washington']::text[]),
('NH', 'OTH', 'curated', 1, 'multiple_choice', 'New Hampshire Motor Speedway, a longtime NASCAR stop, is in which town?', '["Loudon","Concord","Nashua","Laconia"]'::jsonb, 'Loudon', array[]::text[]),
('NH', 'MLB', 'curated', 2, 'multiple_choice', 'Which catcher, raised in New Hampshire, waved his 1975 World Series homer fair?', '["Carlton Fisk","Jason Varitek","Rich Gedman","Gary Carter"]'::jsonb, 'Carlton Fisk', array[]::text[]),
('NH', 'NBA', 'curated', 2, 'multiple_choice', 'Which Concord, NH sharpshooter won two rings with the Spurs?', '["Matt Bonner","Brian Scalabrine","Steve Novak","Kyle Korver"]'::jsonb, 'Matt Bonner', array[]::text[]),
('NH', 'CBB', 'curated', 3, 'free_fill', 'Which Ivy League school plays its home games in Hanover, New Hampshire?', '[]'::jsonb, 'Dartmouth', array['Dartmouth College']::text[]),
('NH', 'OTH', 'curated', 3, 'free_fill', 'The UNH athletic teams go by what nickname?', '[]'::jsonb, 'Wildcats', array[]::text[]),
('NJ', 'NHL', 'curated', 1, 'multiple_choice', 'How many Stanley Cups have the New Jersey Devils won?', '["3","1","2","5"]'::jsonb, '3', array[]::text[]),
('NJ', 'MLB', 'curated', 2, 'multiple_choice', 'Which three-time AL MVP comes from Millville, New Jersey?', '["Mike Trout","Derek Jeter","Todd Frazier","Rick Porcello"]'::jsonb, 'Mike Trout', array[]::text[]),
('NJ', 'NBA', 'curated', 2, 'multiple_choice', 'Which Hall of Fame center was born in Newark?', '["Shaquille O''Neal","Patrick Ewing","Alonzo Mourning","Dikembe Mutombo"]'::jsonb, 'Shaquille O''Neal', array[]::text[]),
('NJ', 'NHL', 'curated', 3, 'free_fill', 'Name the Devils goalie who holds the NHL record for career wins.', '[]'::jsonb, 'Martin Brodeur', array['Brodeur']::text[]),
('NJ', 'CFB', 'curated', 3, 'free_fill', 'Rutgers played the first-ever college football game in 1869 against which school?', '[]'::jsonb, 'Princeton', array['Princeton University']::text[]),
('NM', 'CBB', 'curated', 1, 'multiple_choice', 'What is the nickname of New Mexico''s famously loud basketball arena?', '["The Pit","The Cave","The Furnace","The Crater"]'::jsonb, 'The Pit', array[]::text[]),
('NM', 'CBB', 'curated', 2, 'multiple_choice', 'Which famous championship upset was played at The Pit in 1983?', '["NC State over Houston","Villanova over Georgetown","Texas Western over Kentucky","UMBC over Virginia"]'::jsonb, 'NC State over Houston', array[]::text[]),
('NM', 'NFL', 'curated', 2, 'multiple_choice', 'Which Bears linebacker great played his college ball at New Mexico?', '["Brian Urlacher","Mike Singletary","Lance Briggs","Otis Wilson"]'::jsonb, 'Brian Urlacher', array[]::text[]),
('NM', 'OTH', 'curated', 3, 'free_fill', 'Name the Albuquerque fighter who knocked out Ronda Rousey in 2015.', '[]'::jsonb, 'Holly Holm', array['Holm']::text[]),
('NM', 'OTH', 'curated', 3, 'free_fill', 'Which Albuquerque racing patriarch won the Indy 500 four times?', '[]'::jsonb, 'Al Unser', array['Unser','Al Unser Sr']::text[]),
('NY', 'MLB', 'curated', 1, 'multiple_choice', 'How many World Series titles do the Yankees hold?', '["27","22","25","30"]'::jsonb, '27', array[]::text[]),
('NY', 'NBA', 'curated', 2, 'multiple_choice', 'Which injured Knicks captain walked out of the tunnel to start Game 7 of the 1970 Finals?', '["Willis Reed","Walt Frazier","Dave DeBusschere","Earl Monroe"]'::jsonb, 'Willis Reed', array[]::text[]),
('NY', 'NHL', 'curated', 2, 'multiple_choice', 'The Rangers'' 1994 Stanley Cup ended a drought of how many years?', '["54","40","61","47"]'::jsonb, '54', array[]::text[]),
('NY', 'MLB', 'curated', 3, 'free_fill', 'Which Yankee called himself ''the luckiest man on the face of the earth'' in his 1939 farewell?', '[]'::jsonb, 'Lou Gehrig', array['Gehrig']::text[]),
('NY', 'MLB', 'curated', 3, 'free_fill', 'What nickname did the 1969 championship Mets earn?', '[]'::jsonb, 'Miracle Mets', array['The Miracle Mets','Amazin Mets','Amazins']::text[]),
('NC', 'CBB', 'curated', 1, 'multiple_choice', 'Michael Jordan hit a title-winning shot as a freshman for which school?', '["North Carolina","Duke","NC State","Wake Forest"]'::jsonb, 'North Carolina', array[]::text[]),
('NC', 'CBB', 'curated', 2, 'multiple_choice', 'Which coach won five national titles at Duke?', '["Mike Krzyzewski","Dean Smith","Roy Williams","Jim Valvano"]'::jsonb, 'Mike Krzyzewski', array[]::text[]),
('NC', 'OTH', 'curated', 2, 'multiple_choice', 'Which North Carolina NASCAR king won a record 200 Cup races?', '["Richard Petty","Dale Earnhardt","Junior Johnson","David Pearson"]'::jsonb, 'Richard Petty', array[]::text[]),
('NC', 'CBB', 'curated', 3, 'free_fill', 'Name the coach who ran the court looking for someone to hug after NC State''s 1983 title.', '[]'::jsonb, 'Jim Valvano', array['Valvano','Jimmy V']::text[]),
('NC', 'NFL', 'curated', 3, 'free_fill', 'Which Panthers quarterback won the 2015 NFL MVP?', '[]'::jsonb, 'Cam Newton', array['Newton']::text[]),
('ND', 'OTH', 'curated', 1, 'multiple_choice', 'North Dakota''s famed college hockey team is now nicknamed what?', '["Fighting Hawks","Fighting Sioux","Bison","Ice Cats"]'::jsonb, 'Fighting Hawks', array[]::text[]),
('ND', 'CFB', 'curated', 2, 'multiple_choice', 'Which Fargo school built an FCS dynasty with nine titles in the 2010s?', '["North Dakota State","North Dakota","Minot State","Dickinson State"]'::jsonb, 'North Dakota State', array[]::text[]),
('ND', 'NFL', 'curated', 2, 'multiple_choice', 'Which NDSU quarterback went No. 2 overall in the 2016 draft?', '["Carson Wentz","Trey Lance","Easton Stick","Brock Jensen"]'::jsonb, 'Carson Wentz', array[]::text[]),
('ND', 'MLB', 'curated', 3, 'free_fill', 'Name the Fargo-raised slugger who hit 61 home runs in 1961.', '[]'::jsonb, 'Roger Maris', array['Maris']::text[]),
('ND', 'MLB', 'curated', 3, 'free_fill', 'Which Jamestown, ND native won a World Series with the 2002 Angels after punting for Nebraska?', '[]'::jsonb, 'Darin Erstad', array['Erstad']::text[]),
('OH', 'NFL', 'curated', 1, 'multiple_choice', 'The Browns-Bengals rivalry is known as the Battle of what?', '["Ohio","The Buckeye","Lake Erie","The Rust Belt"]'::jsonb, 'Ohio', array[]::text[]),
('OH', 'NBA', 'curated', 2, 'multiple_choice', 'The 2016 Cavaliers came back from what Finals deficit against Golden State?', '["Down 3-1","Down 3-0","Down 2-0","Down 3-2"]'::jsonb, 'Down 3-1', array[]::text[]),
('OH', 'CFB', 'curated', 2, 'multiple_choice', 'Which third-string quarterback led Ohio State through the first College Football Playoff title run?', '["Cardale Jones","J.T. Barrett","Braxton Miller","Troy Smith"]'::jsonb, 'Cardale Jones', array[]::text[]),
('OH', 'OTH', 'curated', 3, 'free_fill', 'Name the Columbus golfer who holds the record of 18 major championships.', '[]'::jsonb, 'Jack Nicklaus', array['Nicklaus']::text[]),
('OH', 'MLB', 'curated', 3, 'free_fill', 'What was the nickname of the Reds'' mid-1970s championship teams?', '[]'::jsonb, 'Big Red Machine', array['The Big Red Machine']::text[]),
('OK', 'NBA', 'curated', 1, 'multiple_choice', 'Which team did the Thunder beat for the 2025 NBA championship?', '["Indiana Pacers","Boston Celtics","Denver Nuggets","New York Knicks"]'::jsonb, 'Indiana Pacers', array[]::text[]),
('OK', 'CFB', 'curated', 2, 'multiple_choice', 'Oklahoma owns college football''s longest winning streak. How many games?', '["47","34","40","52"]'::jsonb, '47', array[]::text[]),
('OK', 'CFB', 'curated', 2, 'multiple_choice', 'Which former walk-on won the 2017 Heisman at Oklahoma?', '["Baker Mayfield","Kyler Murray","Sam Bradford","Jason White"]'::jsonb, 'Baker Mayfield', array[]::text[]),
('OK', 'MLB', 'curated', 3, 'free_fill', 'Name the Yankees switch-hitter from Commerce, Oklahoma known as the Commerce Comet.', '[]'::jsonb, 'Mickey Mantle', array['Mantle']::text[]),
('OK', 'NBA', 'curated', 3, 'free_fill', 'Which Thunder guard won both MVP and Finals MVP in 2025?', '[]'::jsonb, 'Shai Gilgeous-Alexander', array['SGA','Shai','Gilgeous-Alexander','Gilgeous Alexander']::text[]),
('OR', 'CFB', 'curated', 1, 'multiple_choice', 'Which shoe company grew out of Oregon track, co-founded by runner Phil Knight and coach Bill Bowerman?', '["Nike","Adidas","Brooks","New Balance"]'::jsonb, 'Nike', array[]::text[]),
('OR', 'NBA', 'curated', 2, 'multiple_choice', 'Which center led the Trail Blazers to their 1977 championship?', '["Bill Walton","Clyde Drexler","Arvydas Sabonis","Rasheed Wallace"]'::jsonb, 'Bill Walton', array[]::text[]),
('OR', 'CFB', 'curated', 2, 'multiple_choice', 'Who won Oregon''s first Heisman Trophy in 2014?', '["Marcus Mariota","Joey Harrington","Justin Herbert","LaMichael James"]'::jsonb, 'Marcus Mariota', array[]::text[]),
('OR', 'OTH', 'curated', 3, 'free_fill', 'Name the Coos Bay distance-running icon who died at 24 holding every American record from 2,000 to 10,000 meters.', '[]'::jsonb, 'Steve Prefontaine', array['Prefontaine','Pre']::text[]),
('OR', 'NBA', 'curated', 3, 'free_fill', 'The Blazers famously drafted Sam Bowie in 1984 one pick before which player?', '[]'::jsonb, 'Michael Jordan', array['Jordan','MJ']::text[]),
('PA', 'NFL', 'curated', 1, 'multiple_choice', 'How many Super Bowls have the Steelers won?', '["6","4","5","7"]'::jsonb, '6', array[]::text[]),
('PA', 'NFL', 'curated', 2, 'multiple_choice', 'Franco Harris''s 1972 shoestring catch against the Raiders is known as what?', '["Immaculate Reception","Miracle at the Meadowlands","The Catch","Steel Grab"]'::jsonb, 'Immaculate Reception', array[]::text[]),
('PA', 'CBB', 'curated', 2, 'multiple_choice', 'Whose buzzer-beater won Villanova the 2016 national championship?', '["Kris Jenkins","Ryan Arcidiacono","Josh Hart","Jalen Brunson"]'::jsonb, 'Kris Jenkins', array[]::text[]),
('PA', 'NBA', 'curated', 3, 'free_fill', 'Wilt Chamberlain scored 100 points in 1962 in which Pennsylvania town?', '[]'::jsonb, 'Hershey', array['Hershey PA','Hershey Pennsylvania']::text[]),
('PA', 'OTH', 'curated', 3, 'free_fill', 'Name the golf legend from Latrobe whose ''Army'' followed him to seven majors.', '[]'::jsonb, 'Arnold Palmer', array['Palmer']::text[]),
('RI', 'CBB', 'curated', 1, 'multiple_choice', 'The Providence Friars are a founding member of which basketball conference?', '["Big East","ACC","Atlantic 10","Patriot League"]'::jsonb, 'Big East', array[]::text[]),
('RI', 'CBB', 'curated', 2, 'multiple_choice', 'Which Providence point guard won the 1974 NBA Rookie of the Year?', '["Ernie DiGregorio","Lenny Wilkens","Marvin Barnes","God Shammgod"]'::jsonb, 'Ernie DiGregorio', array[]::text[]),
('RI', 'MLB', 'curated', 2, 'multiple_choice', 'Which Woonsocket native managed the Minnesota Twins starting in 2019?', '["Rocco Baldelli","Dan Hurley","Davey Lopes","Paul Konerko"]'::jsonb, 'Rocco Baldelli', array[]::text[]),
('RI', 'CBB', 'curated', 3, 'free_fill', 'Name the Hall of Fame guard and coach from Providence College who won an NBA title coaching Seattle in 1979.', '[]'::jsonb, 'Lenny Wilkens', array['Wilkens']::text[]),
('RI', 'MLB', 'curated', 3, 'free_fill', 'Which Woonsocket-born early-1900s star hit .426 in 1901, the AL''s highest average ever?', '[]'::jsonb, 'Napoleon Lajoie', array['Lajoie','Nap Lajoie']::text[]),
('SC', 'CFB', 'curated', 1, 'multiple_choice', 'What do Clemson fans call their home stadium?', '["Death Valley","The Swamp","The Plains","Between the Hedges"]'::jsonb, 'Death Valley', array[]::text[]),
('SC', 'CFB', 'curated', 2, 'multiple_choice', 'Which freshman quarterback led Clemson to the 2018 national title over Alabama?', '["Trevor Lawrence","Deshaun Watson","Tajh Boyd","Kelly Bryant"]'::jsonb, 'Trevor Lawrence', array[]::text[]),
('SC', 'CBB', 'curated', 2, 'multiple_choice', 'Who has coached South Carolina''s women to multiple national championships?', '["Dawn Staley","Kim Mulkey","Geno Auriemma","Vivian Stringer"]'::jsonb, 'Dawn Staley', array[]::text[]),
('SC', 'OTH', 'curated', 3, 'free_fill', 'Name the heavyweight champion from Beaufort, SC who handed Muhammad Ali his first pro loss.', '[]'::jsonb, 'Joe Frazier', array['Frazier','Smokin Joe']::text[]),
('SC', 'OTH', 'curated', 3, 'free_fill', 'Which South Carolina Gamecock became a multiple-time WNBA MVP with the Las Vegas Aces?', '[]'::jsonb, 'A''ja Wilson', array['Aja Wilson','Wilson']::text[]),
('SD', 'CFB', 'curated', 1, 'multiple_choice', 'South Dakota State''s teams are known as what?', '["Jackrabbits","Coyotes","Bison","Prairie Dogs"]'::jsonb, 'Jackrabbits', array[]::text[]),
('SD', 'NFL', 'curated', 2, 'multiple_choice', 'Which clutch kicker, raised in Rapid City, won four Super Bowls?', '["Adam Vinatieri","Gary Anderson","Jason Elam","Morten Andersen"]'::jsonb, 'Adam Vinatieri', array[]::text[]),
('SD', 'NBA', 'curated', 2, 'multiple_choice', 'Which Mitchell, SD native won the 2001 NBA Rookie of the Year with Orlando?', '["Mike Miller","Kirk Hinrich","Nate Wolters","Chad Greenway"]'::jsonb, 'Mike Miller', array[]::text[]),
('SD', 'OTH', 'curated', 3, 'free_fill', 'Name the Oglala Lakota runner from Pine Ridge who won stunning 10,000m gold in 1964.', '[]'::jsonb, 'Billy Mills', array['Mills']::text[]),
('SD', 'NBA', 'curated', 3, 'free_fill', 'Which Rapid City point guard became the NBA''s first full-time female assistant coach?', '[]'::jsonb, 'Becky Hammon', array['Hammon']::text[]),
('TN', 'NFL', 'curated', 1, 'multiple_choice', 'The Titans franchise moved to Tennessee from which city?', '["Houston","Baltimore","St. Louis","Memphis"]'::jsonb, 'Houston', array[]::text[]),
('TN', 'NFL', 'curated', 2, 'multiple_choice', 'The Titans'' lateral kickoff-return touchdown in the January 2000 playoffs is called what?', '["Music City Miracle","Nashville Nightmare","Homefield Heist","Volunteer Victory"]'::jsonb, 'Music City Miracle', array[]::text[]),
('TN', 'CBB', 'curated', 2, 'multiple_choice', 'Which Tennessee coach won eight national titles and 1,098 games?', '["Pat Summitt","Bruce Pearl","Rick Barnes","Holly Warlick"]'::jsonb, 'Pat Summitt', array[]::text[]),
('TN', 'CFB', 'curated', 3, 'free_fill', 'Which future Colts legend quarterbacked the Tennessee Volunteers from 1994 to 1997?', '[]'::jsonb, 'Peyton Manning', array['Peyton','Manning']::text[]),
('TN', 'NFL', 'curated', 3, 'free_fill', 'The Titans lost Super Bowl XXXIV when Kevin Dyson was tackled how far from the goal line?', '[]'::jsonb, 'One yard', array['1 yard','a yard','one']::text[]),
('TX', 'NFL', 'curated', 1, 'multiple_choice', 'Which nickname belongs to the Dallas Cowboys?', '["America''s Team","The Lone Stars","Texas''s Team","The Herd"]'::jsonb, 'America''s Team', array[]::text[]),
('TX', 'NFL', 'curated', 2, 'multiple_choice', 'The 1990s Cowboys ''Triplets'' were Troy Aikman, Emmitt Smith, and who?', '["Michael Irvin","Deion Sanders","Jay Novacek","Alvin Harper"]'::jsonb, 'Michael Irvin', array[]::text[]),
('TX', 'NBA', 'curated', 2, 'multiple_choice', 'How many championships did Tim Duncan win with the Spurs?', '["5","3","4","6"]'::jsonb, '5', array[]::text[]),
('TX', 'MLB', 'curated', 3, 'free_fill', 'Name the Texas fireballer who threw a record seven no-hitters.', '[]'::jsonb, 'Nolan Ryan', array['Ryan']::text[]),
('TX', 'CFB', 'curated', 3, 'free_fill', 'Which Tyler, Texas running back won the 1977 Heisman for the Longhorns?', '[]'::jsonb, 'Earl Campbell', array['Campbell','Tyler Rose']::text[]),
('UT', 'NBA', 'curated', 1, 'multiple_choice', 'The Utah Jazz kept their musical name after moving from which city?', '["New Orleans","Memphis","Kansas City","St. Louis"]'::jsonb, 'New Orleans', array[]::text[]),
('UT', 'NBA', 'curated', 2, 'multiple_choice', 'Which Jazz point guard holds the NBA''s all-time assists record?', '["John Stockton","Deron Williams","Mark Jackson","Jason Kidd"]'::jsonb, 'John Stockton', array[]::text[]),
('UT', 'OTH', 'curated', 2, 'multiple_choice', 'Salt Lake City hosted the Winter Olympics in which year?', '["2002","1998","2006","1994"]'::jsonb, '2002', array[]::text[]),
('UT', 'NFL', 'curated', 3, 'free_fill', 'Name the BYU quarterback who threw six touchdowns in Super Bowl XXIX.', '[]'::jsonb, 'Steve Young', array['Young']::text[]),
('UT', 'NBA', 'curated', 3, 'free_fill', 'Michael Jordan''s 1998 ''Last Shot'' in Salt Lake City came over which Jazz defender?', '[]'::jsonb, 'Bryon Russell', array['Russell','Byron Russell']::text[]),
('VT', 'CBB', 'curated', 1, 'multiple_choice', 'Vermont''s athletic teams are known as what?', '["Catamounts","Mountaineers","Green Knights","Lake Monsters"]'::jsonb, 'Catamounts', array[]::text[]),
('VT', 'CBB', 'curated', 2, 'multiple_choice', 'Whose deep three ''from the parking lot'' sealed 13-seed Vermont''s 2005 upset of Syracuse?', '["T.J. Sorrentine","Taylor Coppenrath","Marqus Blakely","Eric Coleman"]'::jsonb, 'T.J. Sorrentine', array[]::text[]),
('VT', 'OTH', 'curated', 2, 'multiple_choice', 'Which Belmont, Vermont snowboarder won halfpipe gold at the 2006 Torino Games?', '["Hannah Teter","Kelly Clark","Gretchen Bleiler","Chloe Kim"]'::jsonb, 'Hannah Teter', array[]::text[]),
('VT', 'NHL', 'curated', 3, 'free_fill', 'Name the St. Albans winger who became the first Vermont-born NHL player with three straight 50-goal seasons for the Flyers.', '[]'::jsonb, 'John LeClair', array['LeClair']::text[]),
('VT', 'OTH', 'curated', 3, 'free_fill', 'Which Rutland-raised skier won two alpine golds at the 1952 Olympics?', '[]'::jsonb, 'Andrea Mead Lawrence', array['Mead Lawrence','Andrea Mead']::text[]),
('VA', 'CBB', 'curated', 1, 'multiple_choice', 'The Virginia Cavaliers play in which conference?', '["ACC","SEC","Big East","Big Ten"]'::jsonb, 'ACC', array[]::text[]),
('VA', 'CBB', 'curated', 2, 'multiple_choice', 'A year after losing to a 16-seed, Virginia did what in 2019?', '["Won the national title","Missed the tournament","Fired its coach","Lost to a 15-seed"]'::jsonb, 'Won the national title', array[]::text[]),
('VA', 'NBA', 'curated', 2, 'multiple_choice', 'Which Hampton, Virginia guard won the 2001 NBA MVP?', '["Allen Iverson","Alonzo Mourning","Grant Hill","Jerry Stackhouse"]'::jsonb, 'Allen Iverson', array[]::text[]),
('VA', 'OTH', 'curated', 3, 'free_fill', 'Name the Richmond tennis pioneer who won Wimbledon in 1975.', '[]'::jsonb, 'Arthur Ashe', array['Ashe']::text[]),
('VA', 'NFL', 'curated', 3, 'free_fill', 'Which Williamsburg-born Giants linebacker redefined the position and won two Super Bowls?', '[]'::jsonb, 'Lawrence Taylor', array['Taylor','LT']::text[]),
('WA', 'NFL', 'curated', 1, 'multiple_choice', 'What do Seahawks fans collectively call themselves?', '["The 12s","The Flock","The Wave","The Green Wall"]'::jsonb, 'The 12s', array[]::text[]),
('WA', 'NFL', 'curated', 2, 'multiple_choice', 'What was the final score of the Seahawks'' Super Bowl XLVIII rout of Denver?', '["43-8","35-10","28-3","48-7"]'::jsonb, '43-8', array[]::text[]),
('WA', 'NFL', 'curated', 2, 'multiple_choice', 'Seattle''s Super Bowl XLIX loss ended on a goal-line interception by which Patriot?', '["Malcolm Butler","Darrelle Revis","Devin McCourty","Brandon Browner"]'::jsonb, 'Malcolm Butler', array[]::text[]),
('WA', 'MLB', 'curated', 3, 'free_fill', 'Name ''The Kid'' — the Mariners center fielder with 630 career home runs.', '[]'::jsonb, 'Ken Griffey Jr', array['Griffey','Ken Griffey','Ken Griffey Junior']::text[]),
('WA', 'MLB', 'curated', 3, 'free_fill', 'Which Mariners ace threw a perfect game in 2012?', '[]'::jsonb, 'Felix Hernandez', array['Hernandez','King Felix']::text[]),
('WV', 'CFB', 'curated', 1, 'multiple_choice', 'Which song do West Virginia fans sing after every home win?', '["Take Me Home, Country Roads","Sweet Caroline","Rocky Top","Mr. Brightside"]'::jsonb, 'Take Me Home, Country Roads', array[]::text[]),
('WV', 'NBA', 'curated', 2, 'multiple_choice', 'Which West Virginia native''s silhouette is widely said to be the NBA logo?', '["Jerry West","Hal Greer","Rod Hundley","George King"]'::jsonb, 'Jerry West', array[]::text[]),
('WV', 'NFL', 'curated', 2, 'multiple_choice', 'Which Rand, WV receiver starred at Marshall before his Hall of Fame NFL career?', '["Randy Moss","Chad Pennington","Troy Brown","Byron Leftwich"]'::jsonb, 'Randy Moss', array[]::text[]),
('WV', 'OTH', 'curated', 3, 'free_fill', 'Name the Fairmont gymnast who won the 1984 Olympic all-around.', '[]'::jsonb, 'Mary Lou Retton', array['Retton']::text[]),
('WV', 'NFL', 'curated', 3, 'free_fill', 'Which WVU linebacker anchored the Giants'' defense in the 1950s and landed in the Hall of Fame?', '[]'::jsonb, 'Sam Huff', array['Huff']::text[]),
('WI', 'NFL', 'curated', 1, 'multiple_choice', 'What makes the Packers unique among major U.S. pro teams?', '["Publicly owned by fans","No home stadium","Oldest logo","Two home cities"]'::jsonb, 'Publicly owned by fans', array[]::text[]),
('WI', 'NFL', 'curated', 2, 'multiple_choice', 'The 1967 NFL Championship at Lambeau, played at -13°F, is known as what?', '["Ice Bowl","Freezer Bowl","Snow Bowl","Frost Bowl"]'::jsonb, 'Ice Bowl', array[]::text[]),
('WI', 'NBA', 'curated', 2, 'multiple_choice', 'How many points did Giannis score in the Bucks'' 2021 title-clinching Game 6?', '["50","42","45","55"]'::jsonb, '50', array[]::text[]),
('WI', 'NFL', 'curated', 3, 'free_fill', 'The Super Bowl trophy is named for which Packers coach?', '[]'::jsonb, 'Vince Lombardi', array['Lombardi']::text[]),
('WI', 'MLB', 'curated', 3, 'free_fill', 'Name the Brewers shortstop-turned-center-fielder who won MVPs at both positions.', '[]'::jsonb, 'Robin Yount', array['Yount']::text[]),
('WY', 'CFB', 'curated', 1, 'multiple_choice', 'Wyoming''s War Memorial Stadium is the highest in FBS at what elevation?', '["7,220 feet","5,280 feet","6,035 feet","8,100 feet"]'::jsonb, '7,220 feet', array[]::text[]),
('WY', 'NFL', 'curated', 2, 'multiple_choice', 'Which Bills star quarterback played his college ball at Wyoming?', '["Josh Allen","Jim Kelly","Carson Wentz","Jay Cutler"]'::jsonb, 'Josh Allen', array[]::text[]),
('WY', 'CBB', 'curated', 2, 'multiple_choice', 'Wyoming won the NCAA basketball title in 1943 behind which jump-shot pioneer?', '["Kenny Sailors","Bob Kurland","Hank Luisetti","George Mikan"]'::jsonb, 'Kenny Sailors', array[]::text[]),
('WY', 'OTH', 'curated', 3, 'free_fill', 'Name the Afton, Wyoming wrestler who beat the unbeatable Alexander Karelin for 2000 Olympic gold.', '[]'::jsonb, 'Rulon Gardner', array['Gardner']::text[]),
('WY', 'OTH', 'curated', 3, 'free_fill', 'Cheyenne hosts ''the Daddy of ''em All,'' the world''s largest outdoor what?', '[]'::jsonb, 'Rodeo', array['Frontier Days','Cheyenne Frontier Days']::text[])
) as v(territory_id, sport, link_type, tier, format, question_text, options, correct_answer, aliases);

create or replace function public.pick_next_question(p_session_id uuid)
returns jsonb
language plpgsql
security definer set search_path = public
as $fn$
declare
  v_session public.game_sessions;
  v_question public.questions;
  v_attempt uuid;
  v_expires timestamptz;
  v_options jsonb;
  v_sports text[];
begin
  select gs.* into v_session from public.game_sessions gs where gs.id = p_session_id for update;
  select g.sports into v_sports from public.seasons s join public.groups g on g.id = s.group_id where s.id = v_session.season_id;

  select qq.* into v_question
  from public.questions qq
  where qq.territory_id = v_session.territory_id
    and qq.active
    and not exists(
      select 1 from public.season_question_seen sqs
      where sqs.season_id = v_session.season_id and sqs.question_id = qq.id and sqs.served_to = v_session.user_id
    )
  order by case when qq.sport = any(v_sports) then 0 else 1 end, abs(qq.tier - v_session.tier), random()
  limit 1;

  if not found then
    -- Every question for this state has been seen by this player: recycle the
    -- least recently served one rather than making the state unplayable.
    select qq.* into v_question
    from public.questions qq
    join public.season_question_seen sqs
      on sqs.season_id = v_session.season_id and sqs.question_id = qq.id and sqs.served_to = v_session.user_id
    where qq.territory_id = v_session.territory_id and qq.active
    order by sqs.served_at asc, abs(qq.tier - v_session.tier)
    limit 1;
    if not found then raise exception 'This state is temporarily out of unused questions'; end if;
    update public.season_question_seen set served_at = now()
    where season_id = v_session.season_id and question_id = v_question.id and served_to = v_session.user_id;
  else
    insert into public.season_question_seen(season_id, question_id, served_to) values (v_session.season_id, v_question.id, v_session.user_id);
  end if;

  v_expires := now() + case when v_question.tier = 3 then interval '45 seconds' else interval '30 seconds' end;
  insert into public.question_attempts(session_id, question_id, user_id, expires_at)
  values (p_session_id, v_question.id, v_session.user_id, v_expires) returning id into v_attempt;
  update public.game_sessions set current_attempt_id = v_attempt where id = p_session_id;

  select coalesce(jsonb_agg(value order by md5(value || v_attempt::text)), '[]'::jsonb) into v_options
  from jsonb_array_elements_text(v_question.options);

  return jsonb_build_object(
    'attempt_id', v_attempt,
    'text', v_question.question_text,
    'format', v_question.format,
    'options', v_options,
    'tier', v_question.tier,
    'sport', v_question.sport,
    'link_type', v_question.link_type,
    'expires_at', v_expires
  );
end;
$fn$;
